In [1]:
import pandas as pd
import numpy as np

In [49]:
#Question no 1

from numpy.random import randint as ri
a = ri(2,6,16).reshape(4,-1)

print("Original Array: \n",a)

print("-"*20)

add_rows=np.array(range(0,a.shape[0]))

print("After:\n",a ** add_rows) #ROW BROADCASTING

Original Array: 
 [[3 3 5 2]
 [4 2 3 5]
 [4 5 3 5]
 [2 2 5 3]]
--------------------
After:
 [[  1   3  25   8]
 [  1   2   9 125]
 [  1   5   9 125]
 [  1   2  25  27]]


In [66]:
# Question no 2
l1 = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
n=len(l1)
res=[]
sum
for i in range(0,n-k+1):
    sum = 0
    for j in range(0,k):
        sum = sum + l1[i+j]
    res.append(sum/4)
print(res)

[3.75, 3.5, 4.25, 5.0, 7.25, 21.5, 37.0, 54.5, 63.0, 70.0, 87.25]
